[project]
name = "flights-schedule-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ics>=0.7.0",
    "pdfplumber>=0.7.0",
    "streamlit>=1.28.0",
]
